### ISSUE TITLE
Display (block instead of in-line)

### ISSUE THREAD

**Issue by suryaarukonda** [The-WebOps-Club/nirmaan-website#2]
As i replicated the page of E-cell nirmaan (http://www.ecell.iitm.ac.in/nirmaan/), I am unable to figure out the problem involved in the navigation bar(i.e; elements in it showing the display as block instead of in-line).

The following code is replicated code with modifications,

`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Nirmaan</title>
    <meta name="description" content="Free Bootstrap Theme by BootstrapMade.com">
    <meta name="keywords" content="free website templates, free bootstrap themes, free template, free bootstrap, free website template">
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <link rel="shortcut icon" href="img/title.png" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Fira+Sans|Roboto:300,400|Questrial|Satisfy">
    <link rel="stylesheet" type="text/css" href="css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="css/animate.css">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    
    
  </head>
  <body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">
  <div class="header">
      <div class="bg-color">
        <header id="main-header">
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container">
            <div class="navbar-header" style="  float: left; width: 20%;">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#lauraMenu">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#" >
                <img src="img/nirmaan.png" width="55%" style="padding: 0;">

              </a>
            </div>
            <div class="collapse navbar-collapse" id="lauraMenu" style="float: right; width: 80%;">
              <ul class="nav navbar-nav navbar-right navbar-border">
                <li class="active tablit"><a href="#main-header">Home</a></li>
                <li class="tablit"><a href="#about">What is <span class="nirmaan">Nirmaan</span>?</a></li>
                <li class="tablit"><a href="#testimonial">What is in it for you?</a></li>
                <li class="tablit"><a href="#contact">How to join the program?</a></li>
				<li class="tablit"><a href="file:///home/suryaarukonda/nirmaan-website/login/index.html">login</a></li>
                <li class="tablit"><a href="file:///home/suryaarukonda/nirmaan-website/register/register.html">registration</a></li>
                
              </ul>
            </div>
          </div>
        </nav>
        </header>
        <div class="wrapper">
        <div class="container">
          <div class="row">
            <div class="col-md-12 wow fadeIn delay-05s">
              <div class="banner-text">
                <h2><span class="tablit">Nirmaan</span> is the pre-incubation cell of IIT Madras</h2>
                <p>There are a lot of students in institute who have ideas for startups. A lot of students who want to work on startups. But for doing that, there is a huge jump which teams need to make to get into the incubated. They require the product, the business model and a good team. We understand that it’s not possible to take such a drastic jump by ourselves and hence, launched this pre-incubation cell to take students from idea-stage to startup stage. </p>
              <h2 style="text-align: center;"><span class="tablit">"Experience Entrepreneurship</span> @ IITM"</h2>

              </div>
              <div class="overlay-detail text-center">
                  <a href="#about"><i class="fa fa-angle-down"></i></a>
              </div>
            </div>
          </div>
          </div>
        </div>
        </div>
      </div>
      <br><br><br>
  <section id="about" class="section-padding wow fadeIn delay-05s">
    <div class="container">
      <div class="row">
        <div class="col-md-6 text-right">
          <h2 class="title-text">
            Why <br><span class="deco tablit">Nirmaan</span>?
          </h2>
        </div>
        <div class="col-md-6 text-left">
          <div class="about-text">
            <p><b>•</b> Setting up a long term program to facilitate the students to think beyond just placements!</p>
            <p>&nbsp;</p>
            <p><b>•</b> To prepare the students to graduate to the Incubation Cell at IIT Madras and grow further by giving them a feel of a start-up as well as providing seed funding for their projects.</p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section id="testimonial" class="section-padding wow fadeInUp">
    <div class="container">
      <div class="row">
        <h2 class="title text-center">What is in it for <span class="deco tablit">You</span>?</h2>
        <div class="test-sec">
          <div class="col-sm-4">
            <blockquote>
              <p>Staged funding opportunities, which can go upto INR 2 Lacs</p>
            </blockquote>
          </div>
          <div class="col-sm-4">
            <blockquote>
              <p>Office space in CFI and other workshop facilities.</p>
            </blockquote>
          </div>
          <div class="col-sm-4">
            <blockquote>
              <p>Network with alumni and entrepreneurs often coming to Insti</p>
            </blockquote>
          </div>
        </div>
        <div class="test-sec">
          <div class="col-sm-4">
            <blockquote>
              <p>Collaborations with TiE, RTBI, Incubation Cell for guidance over business aspects.</p>
            </blockquote>
          </div>
          <div class="col-sm-4">
            <blockquote>
              <p>A series of conferences with top-notch entrepreneurs and venture capitalists.</p>
            </blockquote>
          </div>
          <div class="col-sm-4">
            <blockquote>
              <p>Potential conversion your participation into a 3-credit free elective.</p>
            </blockquote>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section id="contact" class="section-padding wow fadeIn delay-05s">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="contact-sec text-center">
            <h2>How to join the <span class="deco">program</span>?</h2>

              <ul class="list-group">
                <div class="row" style="padding-bottom: 8px!important;">
                  <div class="col-sm-3"></div>
                  <li class="list-group-item col-sm-6 lit" style="padding: 20px 40px;">The program is open to current students of all degree programs of IIT Madras. You must have completed atleast 2 years (1 year for M-Tech and MBA students).</li>
                  <div class="col-sm-3"></div>
                </div><div class="row" style="padding-bottom: 8px!important;">
                  <div class="col-sm-3"></div>
                  <li class="list-group-item col-sm-6 lit" style="padding: 20px 40px;">Brilliant ideas from exceptional second year students will also be accepted on case-to-case basis.</li>
                  <div class="col-sm-3"></div>
                </div><div class="row" style="padding-bottom: 8px!important;">
                  <div class="col-sm-3"></div>
                  <li class="list-group-item col-sm-6 lit" style="padding: 20px 40px; text-align: left;">Startup ideas falling under one of the below themes of national importance will be prefered:
             <ul class="abt-list listof" style="text-align: left;">

              <li style="padding-top: 4px;" class="tablit">• Education Technogy</li>
              <li class="tablit">• Fin Tech</li>
              <li class="tablit">• Healthcare</li>
              <li class="tablit">• Water and Sanitation</li>
              <li class="tablit">• Waste management</li>
              <li class="tablit">• Energy</li>
              <li class="tablit">• Agriculture</li>
              <li class="tablit">• Transportation and environment</li>
              <li class="tablit">• Affordable housing</li>
              <li class="tablit">• Assistive technology</li>
            </ul>

                  </li>

                  <div class="col-sm-3"></div>

                </div>
              </ul>

             ho
          </div>
        </div>
        
        <div class="col-md-8 col-md-push-2">
            <div id="sendmessage">Your details have been sent. Thank you!</div>
            <div id="errormessage"></div>
        </div>
          
      </div>
    </div>

  </section>
  <footer class="footer-2 text-center-xs bg--white">
    <div class="container">
      
      <div class="row">
          <div class="col-md-8">
              <div class="footer">
                    <div class="credits" style="display: inline-block;white-space: nowrap;">
                        <a href="https://ecell.bitballoon.com/" target="_blank">
                        <img src="img/ecell_logo.png" width="33%" style="margin-right: 5%;">
                        </a>
                        <a href="http://cfi.iitm.ac.in/main/" target="_blank">
                        <img src="img/p1.jpg" width="10%" style="margin-right: 5%;">
                        </a>
                        <a href="https://www.iitm.ac.in/" target="_blank">
                        <img src="img/p2.jpg" width="8%">
                        </a>

                    </div>
              </div>
          </div>
          <div class="col-md-4 text-right" style="">
              <ul class="social-list" style="line-height: 53px; transform: scale(1.1);">
                  <li>Follow us on:  &nbsp;
                      <a href="https://www.facebook.com/ECELLIITM/" target="_blank">
                          <i class="fa fa-facebook"></i>
                      </a>
                  </li>
              </ul>
          </div>
          
      </div>
      
    </div>
  </footer>
  
    <script src="js/jquery.min.js"></script>
    <script src="js/jquery.easing.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.bxslider.min.js"></script>
    <script src="js/wow.js"></script>
    <script src="js/custom.js"></script>
    <
    
  </body>
</html>`

**Comment by chinnichaitanya** [comment]
@vaporwave123 Please comment the commit which closes this issue

**Comment by raghul-rajasekar** [comment]
https://github.com/The-WebOps-Club/nirmaan-website/commit/cf55ee56936c51b1e03ef7622a519b68a593061f
