### ISSUE TITLE
Make all links relative

### ISSUE THREAD

**Issue by shahidhk** [The-WebOps-Club/nirmaan-website#3]
All links to CSS/JS files as well as a hrefs should be relative. Do not use absolute links starting with file://

**Comment by chinnichaitanya** [comment]
@vaporwave123 Please do mention the commit which closes this issue.

**Comment by raghul-rajasekar** [comment]
https://github.com/The-WebOps-Club/nirmaan-website/commit/f1af2345f1f14e9f4af69595937d501ea3448c18
